# -*- coding: utf-8 -*-
"""exercise_matplotlib_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/engqroz-io/bootcamp_dio_python_data_analytics_labs/blob/main/exercise_matplotlib_1.ipynb
"""

import matplotlib

from sklearn.datasets import make_regression
x, y = make_regression(n_samples=200, n_features=1, noise=30)

import matplotlib.pyplot as plt

plt.scatter(x,y)
plt.show()